services:
    # image project
    app:
        build:
            context: ./src
            dockerfile: Dockerfile
        restart: no
        user: "1000"
        working_dir: /app/src
        command: sh startup.sh ${ENV:-local} ${DB_PW:-password}
        volumes:
            - ./src:/app/src
        ports:
            - "${API_PORT:-8016}:8000"
        networks:
            - app
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        restart: no
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_ROOT_PASSWORD: '${DB_PW:-password}'
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=${DB_PW:-password} || exit 1
            interval: 5s
            retries: 2
            start_period: 5s
            timeout: 10s
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - "${DB_PORT:-3316}:3306"
        networks:
            - app

networks:
    app:
        driver: bridge
