
#CD GitHub Actions Workflow
name: CD

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [devel, staging, main]

jobs:
  deploy-production:
    if: github.ref_name == 'main'
    # needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/dev/laravel-products-api/
            git pull origin main
            ENV=production API_PORT=${{ vars.API_PORT }} DB_PORT=${{ vars.DB_PORT }} DB_PW=${{ secrets.DB_PW }} docker compose up -d --build